/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AboutSection = {
  _id: string;
  _type: "aboutSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  aboutImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  copyright?: string;
  instagram?: string;
  email?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  welcomeText?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: "wedding" | "concert" | "portrait" | "landscape";
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | AboutSection
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | HomePage
  | Project
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../lib/sanity.queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(_createdAt desc) {  _id,  title,  mainImage,  "slug": slug.current}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  slug: string | null;
}>;

// Source: ../lib/sanity.queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {  _id,  title,  description,  mainImage,  gallery,  "slug": slug.current}
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  description: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  slug: string | null;
} | null;

// Source: ../lib/sanity.queries.ts
// Variable: HERO_QUERY
// Query: *[_type == "homePage"][0] {  title,  welcomeText,  heroImage}
export type HERO_QUERY_RESULT = {
  title: string | null;
  welcomeText: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: ../lib/sanity.queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {  copyright,  instagram,  email}
export type SETTINGS_QUERY_RESULT = {
  copyright: string | null;
  instagram: string | null;
  facebook: string | null;
  youtube: string | null;
  email: string | null;
} | null;

// Source: ../lib/sanity.queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "aboutSection"][0] {  title,  aboutImage,  description}
export type ABOUT_QUERY_RESULT = {
  title: string | null;
  aboutImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
} | null;

// Source: ../lib/sanity.queries.ts
// Variable: CONTACT_QUERY
// Query: *[_type == "contactSection"][0] {  title,  text,  submitButtonText}
export type CONTACT_QUERY_RESULT = {
  title: string | null;
  text: string | null;
  submitButtonText: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "project"] | order(_createdAt desc) {\n  _id,\n  title,\n  mainImage,\n  "slug": slug.current\n}': PROJECTS_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug][0] {\n  _id,\n  title,\n  description,\n  mainImage,\n  gallery,\n  "slug": slug.current\n}': PROJECT_BY_SLUG_QUERY_RESULT;
    '*[_type == "homePage"][0] {\n  title,\n  welcomeText,\n  heroImage\n}': HERO_QUERY_RESULT;
    '*[_type == "siteSettings"][0] {\n  copyright,\n  instagram,\n  email\n}': SETTINGS_QUERY_RESULT;
    '*[_type == "aboutSection"][0] {\n  title,\n  aboutImage,\n  description\n}': ABOUT_QUERY_RESULT;
    '*[_type == "contactSection"][0] {\n  title,\n  text,\n  submitButtonText\n}': CONTACT_QUERY_RESULT;
  }
}
